services:
  mysql:
    image: mysql:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  python:
    build:
      context: ..
      dockerfile: docker/Dockerfile.python
    container_name: python_container
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000

networks:
  app-network:
    driver: bridge

volumes:
  mysqldata: